# treti pripad pouzitia - natocenie auta je nahodne pred parkovacim miestom alebo sa epizoda zacina z nejakeho miesta v parkovisku
behaviors:
  ParkingCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 20
    checkpoint_interval: 1000000
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 50000
    threaded: true

environment_parameters:
  goal_reward: 1.0
  collision_reward: -0.5
  action_reward: -0.001
  distance_reward_type: 1
  distance_max_reward: 0.001
  rotation_offset: 0.0
  spawn_static_movement_cars: 0
  reverse_factor: 0.1
  parking_section_free_spaces: 5
  spawn_in_front_of_spot: 0.5
  max_rotation: 90.0
