# prvy pripad pouzitia - natocenie auta je nahodne pred parkovacim miestom po cely cas
behaviors:
  ParkingCar:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.0003
      beta: 0.001
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 4
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 4
    max_steps: 20000000
    time_horizon: 128
    summary_freq: 50000
    threaded: true

environment_parameters:
  goal_reward: 1.0
  collision_reward: -0.05
  action_reward: -0.002
  distance_reward_type: 3
  distance_max_reward: 0.001
  rotation_offset: 0.0
  spawn_in_front_of_spot:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: progress
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.04
        value: 1
      - name: Lesson2
        value: 0.6
  max_rotation:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 1
        value: 0.0
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 1
        value: 10.0
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 1
        value: 20.0
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 1
        value: 30.0
      - name: Lesson5
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
        value: 40.0
      - name: Lesson6
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
        value: 50.0
      - name: Lesson7
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
        value: 60.0
      - name: Lesson8
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
        value: 70.0
      - name: Lesson9
        completion_criteria:
          measure: reward
          behavior: ParkingCar
          signal_smoothing: true
          min_lesson_length: 50
          threshold: 0.4
        value: 80.0
      - name: Lesson10
        value: 90.0